services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: portal-bhamada-app
    restart: unless-stopped

    working_dir: /var/www

    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - portal_network


  portal:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: portal-bhamada
    restart: unless-stopped

    depends_on:
      - app

    networks:
      - portal_network
      - caddy_network


  mysql:
    image: mysql:8.4

    container_name: portal-bhamada-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - portal_mysql_data:/var/lib/mysql

    networks:
      - portal_network


volumes:

  portal_mysql_data:


networks:

  portal_network:

  caddy_network:
    external: true
    name: caddy_caddy_network